#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TaskManagerAndroid.Resource", IsApplication=true)]

namespace TaskManagerAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int TaskListLayout = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int btnCreateNewAccount = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int btnCreateProject = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int btnCreateTask = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int btnLogin = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int btnProjectDelete = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int btnProjectEdit = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int btnProjectViewTasks = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int menu_edit = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int projectListLayout = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int scrollTaskList = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int textView2 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int textView3 = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int txtLoginEmail = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int txtLoginPassword = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int txtProjectName = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int txtTaskDescription = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ProjectCreate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ProjectList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ProjectOptions = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Register = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TaskCreate = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TaskList = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int AddItemMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
